#responsible: thomas.hinze@thalesgroup.com
#location: Berlin

'''LWMM2M constants and definitions'''

'''LWM2M clients / endpoints'''
ENDPOINT_ATT = "attus"
ENDPOINT_VZW = "verizonus"
ENDPOINT_MODS = "mods"
ENDPOINT_DEFAULT = "dft"

'''LWM2M Object IDs'''
OBJ_LWM2M_SERVER = 1
OBJ_DEVICE = 3
OBJ_FOTA = 5

'''LWM2M Resource IDs'''
RES_LWM2M_SERVER_LIFETIME = 1

RES_DEVICE_MANUFACTURER = 0
RES_DEVICE_MODEL = 1
RES_DEVICE_SERIAL_NO = 2
RES_DEVICE_FW_VERSION = 3
RES_DEVICE_REBOOT = 4
RES_DEVICE_FACTORY_RESET = 5
RES_DEVICE_POWER_SOURCES = 6
RES_DEVICE_POWER_VOLTAGE = 7
RES_DEVICE_POWER_CURRENT = 8
RES_DEVICE_BATTERY_LEVEL = 9
RES_DEVICE_MEMORY_FREE = 10
RES_DEVICE_ERROR_CODE = 11
RES_DEVICE_RESET_ERROR_CODE = 12
RES_DEVICE_CURRENT_TIME = 13
RES_DEVICE_UTC_OFFSET = 14
RES_DEVICE_TIMEZONE = 15
RES_DEVICE_BINDING_MODES = 16
RES_DEVICE_DEVICE_TYPE = 17
RES_DEVICE_HW_REVISION = 18
RES_DEVICE_SW_REVISION = 19
RES_DEVICE_BATTERY_STATUS = 20
RES_DEVICE_MEMORY_TOTAL = 21
RES_DEVICE_EXT_DEVICE_INFO = 22

RES_FOTA_PACKAGE = 0
RES_FOTA_PACKAGE_URI = 1
RES_FOTA_UPDATE = 2
RES_FOTA_STATE = 3
RES_FOTA_UPDATE_RESULT = 5
RES_FOTA_PACKAGE_NAME = 6
RES_FOTA_PACKAGE_VERSION = 7
RES_FOTA_PROTOCOL_SUPPORT = 8
RES_FOTA_DELIVERY_METHOD = 9

FOTA_UPDATE_STATE_IDLE = 0
FOTA_UPDATE_STATE_DOWNLOAD_IN_PROGRESS = 1
FOTA_UPDATE_STATE_DOWNLOAD_COMPLETE = 2
FOTA_UPDATE_STATE_UPDATE_IN_PROGRESS = 3

FOTA_UPDATE_RESULT_INITIAL = 0
FOTA_UPDATE_RESULT_SUCCESS = 1
FOTA_UPDATE_RESULT_ERR_NO_FLASH = 2
FOTA_UPDATE_RESULT_ERR_NO_MEMORY = 3
FOTA_UPDATE_RESULT_ERR_CONN_LOST = 4
FOTA_UPDATE_RESULT_ERR_INTEGRITY = 5
FOTA_UPDATE_RESULT_ERR_PKG_TYPE_NOT_SUPP = 6
FOTA_UPDATE_RESULT_ERR_INVAL_URI = 7
FOTA_UPDATE_RESULT_ERR_UPDATE_FAILED = 8
FOTA_UPDATE_RESULT_ERR_PROTO_NOT_SUPP = 9

FOTA_PROTOCOL_COAP = 0
FOTA_PROTOCOL_COAPS = 1
FOTA_PROTOCOL_HTTP = 2
FOTA_PROTOCOL_HTTPS = 3
FOTA_PROTOCOL_COAP_OVER_TCP = 4
FOTA_PROTOCOL_COAP_OVER_TLS = 5

FOTA_DELIVERY_METHOD_PUSH = 0
FOTA_DELIVERY_METHOD_PULL = 1
FOTA_DELIVERY_METHOD_BOTH = 2
